# Generated by Django 5.1.6 on 2025-03-11 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0002_remove_property_images_remove_property_videos_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propertyvideo',
            name='property',
        ),
        migrations.AddField(
            model_name='property',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='property_images/'),
        ),
        migrations.AddField(
            model_name='property',
            name='videos',
            field=models.FileField(blank=True, null=True, upload_to='property_videos/'),
        ),
        migrations.AlterField(
            model_name='property',
            name='amenities',
            field=models.CharField(max_length=2000),
        ),
        migrations.DeleteModel(
            name='PropertyImage',
        ),
        migrations.DeleteModel(
            name='PropertyVideo',
        ),
    ]
