# Generated by Django 5.1.6 on 2025-03-11 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_remove_propertyvideo_property_property_images_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.CharField(max_length=255),
        ),
    ]
